### ISSUE TITLE
[FEATURE REQUEST] Ability to use files for [setup.kv_stores] section

### ISSUE THREAD

**Issue by JakeChampion** [fastly/cli#1004]
**Is your feature request related to a problem? Please describe.**
I would like to be able to have a kv store setup section which will use the contents of files for the kv store entries.

**Describe the solution you'd like**
I'd like the solution to match the solution for [local kv stores](https://developer.fastly.com/reference/compute/fastly-toml/#kv-and-secret-stores)
```toml
    [[local_server.kv_stores.example_store]]
      key = "second"
      file = "../test/data/some-object.txt"
```

**Describe alternatives you've considered**
I haven't considered an alternative
