### ISSUE TITLE
fastly compute incorrectly forbids `*` in KV keys

### ISSUE THREAD

**Issue by btsheehy** [fastly/cli#1383]
**Version**
Fastly CLI version v10.17.1 (0ce75689)
Built with go version go1.22.9 linux/amd64 (2025-01-28)
Viceroy version: viceroy 0.12.2

**What happened**

In my `fastly.toml` file, I have a KV store defined:
```toml
  [local_server.kv_stores]
    [[local_server.kv_stores.configs]]
      key = "foo/bar/*"
      file = "./kv/foo-bar-*"
```
When I run `fastly compute serve`, I get this error
```
2025-01-28T19:08:14.651155Z  INFO checking if dictionary adheres to Fastly's API
2025-01-28T19:08:14.711485Z ERROR invalid configuration for 'configs': Invalid `key` value used: Keys for objects cannot contain a `*`.
```

However, [Fastly's docs state that a key can contain an asterisk](https://docs.fastly.com/en/guides/working-with-kv-stores#limitations-and-considerations), which is confirmed by the Fastly site allowing me to do so. 

## EDIT
It would appear a deployed Compute instance will also throw this error, even though the Web UI and docs indicate this should be allowed behavior.
