### ISSUE TITLE
ERROR: error parsing rustup constraint: improper constraint: .

### ISSUE THREAD

**Issue by jackxbritton** [fastly/cli#326]
**Version**

0.32.0.

**What happened**

`fastly compute build`, running in my CI, triggers the error `ERROR: error parsing rustup constraint: improper constraint: .`. My project did not trigger this error in 0.31.0. I believe this is the same bug from https://github.com/fastly/cli/issues/258, which was patched but has regressed in this new version.

Note that I am able to build the project locally, but again, *not* in CI. This is consistent with the behavior described in the linked issue.

**Comment by Integralist** [comment]
Thanks @jackxbritton I'm looking into this currently.

**Comment by Integralist** [comment]
Just to confirm you're running the same 0.32.0 both locally _and_ on CI, is that correct? 

I'm asking as it seems odd that locally would build fine but CI wouldn't (if they're both running the same CLI version). That said I'm seeing this in a test file I'm running so I'm able to replicate the error at least which gives me something to dig into further.

Thanks.

**Comment by Integralist** [comment]
Hi @jackxbritton I've not been able to replicate the issue.

Can you try running `fastly configure` and let me know what the output is, and also if you could share the contents of your `config.toml` (the command should display the path to the config -- just be sure to redact any sensitive info such as `email` and `token`).

Thanks.

**Comment by cmac4603** [comment]
I've also just started seeing this:
```toml
[cli]
  last_checked = "2021-07-06T15:51:08+01:00"
  remote_config = ""
  ttl = ""
  version = "0.32.0"

[fastly]
  api_endpoint = "https://api.fastly.com"

[language]

  [language.rust]
    fastly_sys_constraint = ""
    rustup_constraint = ""
    toolchain_version = ""
    wasm_wasi_target = ""

[legacy]
  email = ""
  token = ""

[starter-kits]

[user]
  email = "xxxxxxxxxx"
  token = "xxxxxxxxxxx"
```
I've tried removing the `rustup_constraint`, but it just gets re-added on any command run

**Comment by cmac4603** [comment]
I just downgraded to `0.31.0` and everything works again with a lot more info in the config file:
```toml

[cli]
  last_checked = "2021-07-06T16:01:08+01:00"
  remote_config = "https://developer.fastly.com/api/internal/cli-config"
  ttl = "5m"
  version = "0.31.0"

[fastly]
  api_endpoint = "https://api.fastly.com"

[language]

  [language.rust]
    fastly_sys_constraint = ">= 0.3.3 < 0.5.0"
    rustup_constraint = ">= 1.23.0"
    toolchain_version = "1.49.0"
    wasm_wasi_target = "wasm32-wasi"

[legacy]
  email = ""
  token = ""

[starter-kits]

  [[starter-kits.assemblyscript]]
    branch = ""
    name = "Default"
    path = "https://github.com/fastly/compute-starter-kit-assemblyscript-default"
    tag = "v0.2.1"

  [[starter-kits.rust]]
    branch = "0.7"
    name = "Default"
    path = "https://github.com/fastly/compute-starter-kit-rust-default.git"
    tag = ""

  [[starter-kits.rust]]
    branch = ""
    name = "Beacon"
    path = "https://github.com/fastly/compute-starter-kit-rust-beacon-termination.git"
    tag = ""

  [[starter-kits.rust]]
    branch = ""
    name = "Static"
    path = "https://github.com/fastly/compute-starter-kit-rust-static-content.git"
    tag = ""

[user]
  email = "xxxxxxxx"
  token = "xxxxxxxx"
```
