### ISSUE TITLE
Rustup toolchain check prevents deploy if newest installed toolchain is incompatible

### ISSUE THREAD

**Issue by ccampbell** [fastly/cli#363]
**Version**

```
Fastly CLI version 0.36.0 (dd0b7d9)
Built with go version go1.16.6 linux/amd64
```

**What happened**

I recently updated my project’s rust-toolchain to use 1.54.0 which is [not currently supported in the CLI](https://github.com/fastly/cli/blob/dd0b7d95750beb23e735151f73945e69660dbff1/cmd/fastly/static/config.toml#L13). It returns the following error which is expected:
> ERROR: rust toolchain 1.54.0 is incompatible with the constraint >= 1.49.0 < 1.54.0

However, the issue is that even after changing my local `rust-toolchain` file to use 1.53.0 which _is_ compatible, the deployment still fails because the [check for the toolchain version](https://github.com/fastly/cli/blob/28370af78585c98d884dd78162a8eb697c4e59b0/pkg/commands/compute/language_rust.go#L410) explicitly uses the last version you have installed locally based on `rustup toolchain list`. For me the list (after updating `rust-toolchain`) is:
```
1.43.0-x86_64-apple-darwin
1.46.0-x86_64-apple-darwin
1.49.0-x86_64-apple-darwin
1.51.0-x86_64-apple-darwin (default)
1.53.0-x86_64-apple-darwin (override)
1.54.0-x86_64-apple-darwin
```

I think it may make sense to use `rustup show active-toolchain` to pull in the toolchain version since that one should respect the one actually being used by the project. Output of that command is:

```
1.53.0-x86_64-apple-darwin (overridden by '/path/to/project/rust-toolchain')
```

**Comment by berniechiu** [comment]
Just encountered this issue when we have a CI build, but we've only installed a single version, using the `rustup toolchain list` shouldn't matter

This is our example CI
```yaml
env:
  CARGO_TERM_COLOR: always
  FASTLY_CLI_VERSION: v0.27.2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: 1.49.0
        target: wasm32-wasi
...
...
    - name: Build wasm package
      run: ./fastly compute build
      env:
        FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }
```

![截圖 2021-08-10 上午11 24 52](https://user-images.githubusercontent.com/2749593/128803637-fe615417-c8ab-46bb-8d8c-f7ab072c623c.png)
