### ISSUE TITLE
non-standard port used for backend setup causes cli to fail parsing fastly.toml

### ISSUE THREAD

**Issue by JakeChampion** [fastly/cli#592]
**Version**

Fastly CLI version v3.1.1 (59efd38)
Built with go version go1.18.3 linux/amd64
Viceroy version: viceroy 0.2.14

**What happened**

When a backend in the `setup` section uses a port other than 443 or 80,  the CLI will error.
This is likely a bug as in the Fastly Web UI, a backend can be created with any port number

```
❯ fastly compute publish -i
✓ Initializing...
✗ Verifying package manifest...

ERROR: error parsing package manifest.

Run `fastly compute init` to ensure a correctly configured manifest. See more at https://developer.fastly.com/reference/fastly-toml/
```

```toml
authors = ["me@jakechampion.name"]
description = ""
language = "other"
manifest_version = 2
name = "example"
service_id = ""

[scripts]
  build = "mkdir -p bin && cargo run --release app.js bin/main.wasm"

[setup]

  [setup.backends]

    [setup.backends.TelemetryServer]
      address = "example.com"
      port = "8081"

# [local_server]

#   [local_server.backends]

#     [local_server.backends.TelemetryServer]
#       url = "http://localhost:8081/"
```
