### ISSUE TITLE
😵‍💫 Starter kit `Cargo.toml` loses its formatting

### ISSUE THREAD

**Issue by acfoltzer** [fastly/cli#597]
**Version**

```
❯ fastly version
Fastly CLI version v3.1.1 (59efd38)
Built with go version go1.18.3 linux/amd64
Viceroy version: viceroy 0.2.14
```

**What happened**

Ran `fastly compute init` and chose the empty Rust starter kit. The resulting `Cargo.toml` looked like:

```toml

[dependencies]
  fastly = "^0.8.2"

[package]
  edition = "2021"
  name = "my-new-project"
  publish = false
  version = "0.1.0"

[profile]

  [profile.release]
    debug = 1
```

While semantically correct, the formatting does not match the [starter kit](https://github.com/fastly/compute-starter-kit-rust-empty/blob/8644490363da58f50f448988f2cfb6fe79b6a48a/Cargo.toml#L1-L13)'s formatting and comments. The resulting formatting, alphabetized with indentation, is extremely surprising to a Rust programmer.
