### ISSUE TITLE
[BUG] fastly cli removes a valid section from fastly.toml file when updating the file

### ISSUE THREAD

**Issue by JakeChampion** [fastly/cli#648]
**Version**

Fastly CLI version v3.3.0 (96b3aa7)
Built with go version go1.19 linux/amd64
Viceroy version: viceroy 0.2.15

**What happened**

I am working on a new C@E application which uses Object Store and I am using the local Object Store feature of Viceroy via fastly.toml.

When I run `fastly compute publish` it removes the section from fastly.toml which relates to local Object Store functionality.

This bug relates to this feature-request: https://github.com/fastly/cli/issues/647

the below section is what got removed.
```toml
[local_server.object_store]
bodies = []
headersAndStatus = []
```

Below is the original fastly.toml file structure I had in my project:
```toml
# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["me@jakechampion.name"]
description = "polyfill.io cdn implemented in javascript"
language = "javascript"
manifest_version = 2
name = "polyfill-service-c-at-e-example"

[local_server.backends.v3_eu]
url = "https://origami-polyfill-service-eu.herokuapp.com"
override_host = "origami-polyfill-service-eu.herokuapp.com"
[local_server.backends.v3_us]
url = "https://origami-polyfill-service-us.herokuapp.com"
override_host = "origami-polyfill-service-us.herokuapp.com"

[local_server.object_store]
bodies = []
headersAndStatus = []

[setup.backends.v3_eu]
address = "origami-polyfill-service-eu.herokuapp.com"
port = 443

[setup.backends.v3_us]
address = "origami-polyfill-service-us.herokuapp.com"
port = 443

```

After running `fastly compute publish` this is what the file looked like:
```toml
# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["me@jakechampion.name"]
description = "polyfill.io cdn implemented in javascript"
language = "javascript"
manifest_version = 2
name = "polyfill-service-c-at-e-example"
service_id = "5NhWgbEeqqUUaC7KeTh92K"

[local_server]

  [local_server.backends]

    [local_server.backends.v3_eu]
      override_host = "origami-polyfill-service-eu.herokuapp.com"
      url = "https://origami-polyfill-service-eu.herokuapp.com"

    [local_server.backends.v3_us]
      override_host = "origami-polyfill-service-us.herokuapp.com"
      url = "https://origami-polyfill-service-us.herokuapp.com"

[setup]

  [setup.backends]

    [setup.backends.v3_eu]
      address = "origami-polyfill-service-eu.herokuapp.com"
      port = 443

    [setup.backends.v3_us]
      address = "origami-polyfill-service-us.herokuapp.com"
      port = 443

```
