### ISSUE TITLE
No Geolocation Data found

### ISSUE THREAD

**Issue by andrewbatallones** [fastly/cli#850]
**Version**

v7.0.0

**What happened**

Command:
```bash
fastly compute serve --addr 0.0.0.0:80 --env=dev --watch
```

This command is run inside a container on Docker. What would happen is if I made any code changes that would trigger a rebuild of the app, the app would crash with this message:
`ERROR request{id=0}: Hostcall yielded an error: No geolocation data: some IP`

**Comment by JakeChampion** [comment]
@andrewbatallones Howdy, do you happen to have a geolocation section in `fastly.toml`?

Something like this:
`fastly.toml`:
```toml
[local_server]
	[local_server.geolocation]
                format = "inline-toml"
                [local_server.geolocation.addresses]
		[local_server.geolocation.addresses."127.0.0.1"]
			as_name = "Dummy, Inc."
			city = "New York"
			latitude = 1.23
			longitude = 1.23
```

or by providing it as an external resource:
`fastly.toml`:
```toml
[local_server]
	[local_server.geolocation]
                format = "json"
		file = "./test-geolocation-data.json"
```

`test-geolocation-data.json`:
```json
{
    "127.0.0.1": {
        "as_name": "Fastly Test",
        "as_number": 12345,
        "area_code": 123,
        "city": "Test City",
        "conn_speed": "broadband",
        "conn_type": "wired",
        "continent": "NA",
        "country_code": "CA",
        "country_code3": "CAN",
        "country_name": "Canada",
        "latitude": 12.345,
        "longitude": 54.321,
        "metro_code": 0,
        "postal_code": "12345",
        "proxy_description": "?",
        "proxy_type": "?",
        "region": "CA-BC",
        "utc_offset": -700
    }
}
```
