### ISSUE TITLE
[FEATURE REQUEST] per-profile api_endpoint

### ISSUE THREAD

**Issue by jamesarosen** [fastly/cli#962]
**Is your feature request related to a problem? Please describe.**
I'd like to use a different `api_endpoint` in different situations and easily switch between the values. For example, I'd like to be able to use `https://api.fastly.com` by default, but `https://api.fastly.com.my-corporate.proxy` when I'm at work. 

**Describe the solution you'd like**

Support `api_endpoint` set on the current profile as an override for the global `fastly.api_endpoint`.

When creating a new profile via `fastly profile create`, I can specify an endpoint, e.g. with `fastly profile create --api-endpoint=https://api.fastly.com.my-corporate.proxy`.

When editing the `fastly/config.toml` directly, I can specify

```toml
[profile]

[profile.work]
default = true
email = "my.work.email@example.com"
token = "fd90safusl32jMO294nk"
api_endpoint = "https://api.fastly.com.my-corporate.proxy"
``` 

**Describe alternatives you've considered**

One alternative would be to add `--api-endpoint` to every other command. Since the Fastly CLI already supports profile-switching (and many commands support single-command profile switching), it seems easier to bundle it into this feature.

**Additional context**

This would also benefit internal Fastly engineers who are using the CLI with pre-production versions of the Fastly API.
